title: Elton Santos
email: eltonaxl@hotmail.com

description: Meu blog pessoal.

baseurl: ""
url: "https://eltonsantos.github.io"
paginate_path: "pagina/:num/"
permalink: /:categories/:title/
category_dir: /

# Social
social:
  linkedin: eltonmelosantos
  twitter: eltin182
  github:  eltonsantos
  gplus: eltin182
  email: eltonaxl@hotmail.com

# Navigation
navigation:
  - title: Home
    url: /
  - title: Sobre mim
    url: /sobre
  - title: Artigos
    url: /artigos
  - title: Devocionais
    url: /devocionais
  
# Build settings
markdown: kramdown
theme: minima

paginate: 10

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

google_analytics: "UA-92973153-1"

exclude:
  - Gemfile
  - Gemfile.lock