title: Elton Santos
email: eltonaxl@hotmail.com

description: Meu blog pessoal.

baseurl: ""
url: "https://eltonsantos.github.io"

# Social
# linkedin_username: eltonmelosantos
# twitter_username: eltin182
# github_username:  eltonsantos
# gplus_username: eltin182

# Social
social:
  linkedin: eltonmelosantos
  twitter: eltin182
  github:  eltonsantos
  gplus: eltin182
  email: eltonaxl@hotmail.com

# Navigation
navigation:
  - title: Home
    url: /
  - title: Artigos
    url: /artigos.html
  - title: Devocionais
    url: /devocionais.html
  
# Build settings
markdown: kramdown
theme: minima

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock