title: Elton Santos
email: eltonaxl@hotmail.com
description: Sou apenas um servo do Deus altíssimo que tem dado a Ele incontáveis razões para não me amar. Nenhuma delas têm sido forte o suficiente para mudá-Lo.
author: Elton Santos
logo: https://avatars3.githubusercontent.com/u/1292594?v=3&s=460

baseurl: ""
url: "https://eltonsantos.github.io"
paginate_path: "pagina/:num/"
permalink: /:categories/:title/
category_dir: /

# Social
social:
  linkedin: eltonmelosantos
  twitter: eltin182
  github:  eltonsantos
  gplus: eltin182
  email: eltonaxl@hotmail.com

# Navigation
navigation:
  - title: Home
    url: /
  - title: Sobre mim
    url: /sobre
  - title: Artigos
    url: /artigos
  - title: Devocionais
    url: /devocionais
  
# Build settings
markdown: kramdown
theme: minima

paginate: 10

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

google_analytics: "UA-92973153-1"

exclude:
  - Gemfile
  - Gemfile.lock